### ISSUE TITLE
Sigma Correlation questions

### ISSUE THREAD

**Issue by gaelmuller** [SigmaHQ/sigma#1311]
I had a look at the Sigma Correlation draft and found it promising :+1: 

I have two questions however:

* Is it strictly required for the rules used by a correlation condition to be in the same file ?
* Given the fact that rules are used to define correlation conditions and that these conditions can be chained, how can we know if an individual rule should raise an alert by itself or is only used for correlation ?

**Comment by thomaspatzke** [comment]
>     * Is it strictly required for the rules used by a correlation condition to be in the same file ?

Thought about this one. I didn't planned it in the first draft, but it makes sense. Will add an include possibility in Sigma rules which allows loading of other files containing Sigma rules.

>     * Given the fact that rules are used to define correlation conditions and that these conditions can be chained, how can we know if an individual rule should raise an alert by itself or is only used for correlation ?

The idea was that only rules and correlations not referred by other correlations will generate queries because the single events of a correlation themself are usually prone to false positives. It makes sense to have the possibility to override this behavior, I will add this to the spec.

Thanks for the inspiration!

**Comment by thomaspatzke** [comment]
Regarding the first point, please check section 2.5 in the [specification](https://1drv.ms/w/s!AmV9jfmd5VQ0uj02_e04EV_Ra-MU). Condition generation rules and overrides are described in 2.4.

**Comment by gaelmuller** [comment]
2.5 looks good to me.

I'm wondering however if it is not too complicated to understand if a rule in itself should generate an alert, especially with the include mechanism. There will be no way to know if the rule is being used by correlations or not by looking at a single file. In order to avoid confusion, I think we could have the `generate` property as required, with a default value to `true`.
