### ISSUE TITLE
Clarification of SIGMA rule behavior (wildcards / full-match)

### ISSUE THREAD

**Issue by maederm** [SigmaHQ/sigma#1365]
Hi

I looked at the detection [powershell_suspicious_keywords.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/powershell/powershell_suspicious_keywords.yml) and the specification of sigma. Am I correct in assuming that this rule only hits on full matches?
E.g. the Message `System.Reflection.Assembly.Load` would match but a Message `System.Reflection.Assembly.Load()` wouldn't? So would this rule even hit on the usage of these keywords?

Another detection [powershell_malicious_commandlets.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/powershell/powershell_malicious_commandlets.yml) uses wildcards around every keyword in the list and therefore would match if the Message contains one of the keywords. Is this correct?

Best, maederm

Ping @ccolic

**Comment by Neo23x0** [comment]
Yes, you've found a bug. 
In an old version of Sigmac, we had a special handling of so-called "keyword" rules.
What I'll do is, add the new modified `contains` to the strings in the first rule and replace the wildcards in the second rule and also use ` |contains` , since this is the new preferred way to write such a rule.

**Comment by maederm** [comment]
Thanks for the clarification
