### ISSUE TITLE
Formatting/Syntax Inconsistencies in builtin/win_apt_apt29_tor.yml

### ISSUE THREAD

**Issue by ikiril01** [SigmaHQ/sigma#2074]
Not sure what the intent was, but there's some strange formatting/syntax issues with https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/win_apt_apt29_tor.yml that's causing my YAML parsing to fail:

* Multiple rules in one file (?)
* Missing `id` on the first rule
* Missing `title`/`description`/etc. on second rule (`c069f460-2b87-4010-8dcf-e45bab362624`)

**Comment by frack113** [comment]
Hello,
I have split all the ["action: global"](https://github.com/SigmaHQ/sigma/wiki/Specification#rule-collections) rule, view discussion #1976 .
But this one is the last because of the `near` and I have not try if one backend works .

sigma can read this type of file very well  [some code here](https://github.com/SigmaHQ/sigma/blob/93493d1c931d76a46a89bbcab2af37381cab68f4/tools/sigma/parser/collection.py#L35)

Maybe it is necessary to move it in "rules-unsupported" for the moment

hope it help

**Comment by frack113** [comment]
Can be close as this rule is move to rules-unsupported

**Comment by ikiril01** [comment]
@frack113 ah I see - thanks for the explanation.
