### ISSUE TITLE
Invalid product field

### ISSUE THREAD

**Issue by asalih** [SigmaHQ/sigma#2115]
Hello team, this rule below has a product definition under log source, which is there is no matching in the configs. Am I missing something, or is this invalid already?

https://github.com/SigmaHQ/sigma/blob/92999468eef9984b0396e2ad211844a953753925/rules/windows/process_creation/process_creation_command_execution_by_office_applications.yml

Thanks for the help.

**Comment by frack113** [comment]
This rule is "bab" in the first place because it is not a process creation rule.
find [this](https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/02bcbfc2bfb8b4da601bb30de0344ae453aa1afe/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml#L49)
perhaps `product: EDR`  and remove `category: process_creation` ?

**Comment by frack113** [comment]
Hi,
I have move the rule to `rules/windows/edr` folder 
change name to `edr_command_execution_by_office_applications.yml`
and `category` to edr

**Comment by frack113** [comment]
Rule was remove.
