### ISSUE TITLE
Likely FPs on "Suspicious Remote Thread Created"

### ISSUE THREAD

**Issue by branchnetconsulting** [SigmaHQ/sigma#2479]
We've chased down hits on [this](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/create_remote_thread/sysmon_suspicious_remote_thread.yml) sigma rule repeatedly, where the PowerPoint executable is seen opening a remote thread in CSRSS.EXE, and we never find any other indicators of compromise.  We've seen it on 5 different Windows 10 end-user systems involving multiple client sites where different AV products are used.  

Source Images seen:
C:\\Program Files (x86)\\Microsoft Office\\Office15\\POWERPNT.EXE
C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE

TargetImage: 
C:\Windows\System32\csrss.exe

When we've traced things down, we've found a legitimate in-house PowerePoint presentation was normally opened, and that the file hash of POWERPNT.EXE checks out clean at VT.

We suspect this is a false positive, but it is perplexing.  Can anyone else think of how POWERPNT.EXE might have a legitimate reason to open a remote thread in CSRSS.EXE?

Kevin

**Comment by Neo23x0** [comment]
Interesting. 

> We suspect this is a false positive, but it is perplexing. Can anyone else think of how POWERPNT.EXE might have a legitimate reason to open a remote thread in CSRSS.EXE?

No. Microsoft magic.

**Comment by nasbench** [comment]
Hi,

I've added a commented filter to the rules in the commit mentioned above to resolve this issue. 

Since we don't have a lot of info about it we can't add it as a main filter for the rule. If someone is experiencing this you could comment it out and it would work.

If this issue is raised by many more people I highly suggest you open a new issue and link back to this one for reference. That way we could include the filter in the rule permanently.
