### ISSUE TITLE
Feature request - Variable usage in sigma rules 

### ISSUE THREAD

**Issue by RaeldZues** [SigmaHQ/sigma#2925]
Is it possible to use variables to compare two fields in one record or log line? I am trying to compare two fields to identify if one contains another and would like the ability to write that in this format. I have posted an image of something I was trying visualize to see if that helps. 

![image](https://user-images.githubusercontent.com/30031151/163849712-6878f03c-8e9a-4fa9-8463-584b9c9e822f.png)

**Comment by Neo23x0** [comment]
Do you mean placeholders? https://github.com/SigmaHQ/sigma/wiki/Specification#placeholders

You can do that. But that doesn't mean that the respective backend supports placeholders.

**Comment by thomaspatzke** [comment]
The proposed syntax is already used for placeholders which are supported by pySigma. Placeholders are generic variables provided to the conversion process. They can't be used for building rules that compare values inside of an event.

We already discussed this in the past and we decided to not add it to the specification because of several reasons:

* It's only a corner case that likely would only be used in very few rules.
* On the opposite, implementing this would add lot of complexity to the conversion backends because this is something that usually isn't handled in the main condition, but in subsequent steps (e.g. in Splunk the `where` command is required for this.
