### ISSUE TITLE
Sigma to elastalert with wildcard queries

### ISSUE THREAD

**Issue by christophetd** [SigmaHQ/sigma#312]
In [this commit](https://github.com/Neo23x0/sigma/commit/ffd43823cf4a7417883c5a489738e5e2bc99c011#diff-dc4715c578cdd6fd295ab24d389da6b3R48) was introduced a way not to quote search queries containing a wildcard. 

For instance, `ProcessName: *WmiPrvSE.exe` will yield the query string `ProcessName:*\\WmiPrvSE.exe`, while `ProcessName: WmiPrvSe.exe` yields `ProcessName:"WmiPrvSE.exe"`.

However, it seems that the regex being used doesn't take into account wildcards preceded by a backslash. So for instance, `ProcessName: 'C:\\Windows\\*\\Taskmgr.exe'` yields `ProcessName:"C\:\\Windows\\*\\Taskmgr.exe"`. This is problematic when we want to match on paths, where the ES query needed would be `ProcessName:C\:\\Windows\\*\\Taskmgr.exe` (no quotes) - what approach would you recommend to do that?

Thank you

**Comment by thomaspatzke** [comment]
This commit fixed the wrong matching behavior with query values containing wildcards. Quickly described, it matches wildcard values against keyword-fields because elsewhere matching will only be done on single tokens instead of the whole value. Further, the correct matching behavior is only done when the value has no quotes around it.

I think the change somehow doesn't fully propagated into the elastalert backend and causes this issue.

**Comment by thomaspatzke** [comment]
Can you point this out on a complete Sigma rule example? I have some issues in reproducing this, as values with wildcards result in keyword-field conversions as desired.
