### ISSUE TITLE
Output from sigmac is unusable for LogPoint due to backslash in (Parent)Image modifier.

### ISSUE THREAD

**Issue by shrikeinfosec** [SigmaHQ/sigma#3200]
The pull request [here](pull/3081) means that there is an additional backslash at the start of the wildcard; when using this query in LogPoint, it will fail due to the double backslash (as LogPoint does not interpret those as escaped characters, but literal characters).

Output: `(Initiated="true" "process"="*\\msiexec.exe")`
![image](https://user-images.githubusercontent.com/107105450/177522853-cc9d0003-55b9-4519-b022-9be8112796cb.png)

Corrected Output: `(Initiated="true" "process"="*\msiexec.exe")`
![image](https://user-images.githubusercontent.com/107105450/177522755-b7d73582-b5cc-4c0e-8e46-64551ec732fe.png)

Is it possible to disable the double backslash (or maybe toggle it somehow)?

*Edit: Just to clarify, I have taken this output from the `net_connection_win_msiexec.yml` rule, but removed the `Initiated` parameter to demonstrate in the screenshots, as I have not mapped this in the backend config yet.*

**Comment by ashcorpdev** [comment]
Just bumping this - any ideas if there is a workaround for this issue (short of just re-writing the queries)?

**Comment by nasbench** [comment]
Hi,

Thanks for opening this issue.

The issue in question you're mentioning isn't related to the PR specifically but to the backend of `logpoint`. It's the standard in SIGMA rule in this repo to use the `endswith` modifier in `image` fields and the idea of SIGMAC is to be able to modify those fields in however you like.

The backend didn't take into consideration these use cases. You can see [here](https://github.com/SigmaHQ/sigma/blob/2d09f84cf55a5763e425d16590276ab5dd424c99/tools/sigma/backends/logpoint.py) in the backend definition it's very barebone with no other conditions or filters.

Anyway to spare you a long explanation. The change needs to be made there. Unfortunately, since SIGMAC is approaching it's EOL the maintenance of some backends is really the best effort as the focus is shifted toward the new PySIGMA.

I can give you a quick fix that I didn't test for all cases but should do the work. From your explanation, you said that the `\` (backslash) isn't needed.

So you can do the following:

- Clone the SIGMA project locally
- Navigate to the `tools\sigma\backends\logpoint.py` and add the following function inside the class (this basically as the name states cleans any value that has a certain character)

```python
def cleanValue(self, val):
        if val.startswith('\\'):
            val = val.replace("\\","")
      
        return val
```
- After this, you can use `sigmac` from the command line as follow

```bash
python tools\sigmac --target logpoint -c tools\config\logpoint-windows.yml [YOUR RULE]
```
Using the same rule as you provided, you get this

![image](https://user-images.githubusercontent.com/8741929/210113059-4f87befb-8b98-44ef-b5f3-76a7636eedb8.png)

**Comment by ashcorpdev** [comment]
Sorry for the late reply, but thank you for going into detail on this, especially given it's on it's way to EOL. I'll take a look at this and tinker around with it when I get the chance.
