### ISSUE TITLE
Syntax error in proc_creation_win_powershell_susp_parameter_variation.yml

### ISSUE THREAD

**Issue by s7ryph** [SigmaHQ/sigma#3271]
The rule proc_creation_win_powershell_susp_parameter_variation contains the following error if used with case sensitive rules.

```
        Image|endswith:
            - '\Powershell.exe'
```

The "P" needs to be changed to lower case to reflect windows logs.

**Comment by wikijm** [comment]
Hi @s7ryph and @frack113

I've made this pull request to correct this Sigma rule: https://github.com/SigmaHQ/sigma/pull/3301

Regards,
WikiJM

**Comment by Neo23x0** [comment]
Sigma rules <are> case-insenstive. If you've indexed data case-senstive or apply the rules case-sensitive, than this is the error.

**Comment by Neo23x0** [comment]
And you should take case of that - imagine the attacker would use `-WindowStyle hidden` instead of `-windowstyle hidden`.

**Comment by frack113** [comment]
Hi,
I have the `create-pull` because it is the only one in rule with a 'P' and not because of the case sensitive.
The funny fact is that the OriginalFileName  is 'PowerShell.EXE'.

https://github.com/SigmaHQ/sigma/wiki/Specification#general 

General
   -  All values are treated as case-insensitive strings  
   -  You can use wildcard characters * and ? in strings (see also escaping section below)
   -  Regular expressions are case-sensitive by default
   -  You don't have to escape characters except the string quotation marks '

**Comment by s7ryph** [comment]
Thank you, I overlooked the case-insensitive section of the Wiki.
