### ISSUE TITLE
Request for XQL

### ISSUE THREAD

**Issue by ryan-4824** [SigmaHQ/sigma#3400]
I’m interested in being able to translating to Palo Alto’s XQL. I’m happy to help translate the fields

**Comment by nasbench** [comment]
Hi,

Thanks for opening this issue and for your interest in creating a backend to translate rules into Palo Alto's XQL.

Since SIGMAC converter is approaching EOL. I would suggest you start writing your backend logic in the new and supported PySIGMA.

You can get started by taking a look a the main repo [here](https://github.com/SigmaHQ/pySigma) and the respective docs [here](https://sigmahq-pysigma.readthedocs.io/en/latest/). You can also check [this](https://micahbabinski.medium.com/creating-a-sigma-backend-for-fun-and-no-profit-ed16d20da142) introductory blog that'll help get started on writing the backend and how PySIGMA works.

Finally, you can also use these PySIGMA backends as templates/inspiration to get the idea 
- [Elastic](https://github.com/SigmaHQ/pySigma-backend-elasticsearch)
- [Insight EDR](https://github.com/SigmaHQ/pySigma-backend-insightidr)
- [Splunk](https://github.com/SigmaHQ/pySigma-backend-splunk)

If you have any further questions or discussion. You could open another issue/discussion here or **preferably** in the [PySIGMA repository](https://github.com/SigmaHQ/pySigma).
