### ISSUE TITLE
[sigmac] [CrowdStrike] CrowdStrike config is not right

### ISSUE THREAD

**Issue by RoemIko** [SigmaHQ/sigma#3579]
When i converted Sigma rules into CrowdStrike rules i noticed that the config is not right. For example: when converting Sigma give `Commandline="* -enc *"` this should be `CommandLine="* -enc *"`. Could this be fixed?

**Comment by thomaspatzke** [comment]
CrowdStrike support in sigmac is broken (e.g. conversion of ParentImage to ParentBaseFileName is also incorrect and will not be fixed anymore, because there is a working implementation of the CrowdStrike FDR data model in [Sigma CLI](https://github.com/SigmaHQ/sigma-cli) with the [CrowdStrike processing pipeline](https://github.com/SigmaHQ/pySigma-pipeline-crowdstrike/).
