### ISSUE TITLE
Exemption on proc_creation_win_creation_mavinject_process_injection.yml

### ISSUE THREAD

**Issue by s7ryph** [SigmaHQ/sigma#3742]
mavinject process should be excluded from devices running App-V as it is normal behavior.  From [LOLBAS Project](https://lolbas-project.github.io/lolbas/Binaries/Mavinject/)

> IOC: mavinject.exe should not run unless APP-v is in use on the workstation

The logic can also be found in the rule on [SentinelOne](https://github.com/keyboardcrunch/SentinelOne-ATTACK-Queries/blob/master/Tactics/DefenseEvasion.md)

Recommend adding ParentImage Not EndsWith '/AppVClient.exe' to the rule to reduce potential false positives.

**Comment by nasbench** [comment]
Hi,

Thanks for opening the issue. Can you please confirm that you're referring to this rule [Mavinject Inject DLL Into Running Process](https://github.com/SigmaHQ/sigma/blob/a674ee246bd02271f5e46d00010320112c9df17c/rules/windows/process_creation/proc_creation_win_creation_mavinject_process_injection.yml#L2)

Also, in the SentinelOne link you mentioned what's the `SrcProcName` referring to? I don't think it's the parent, since I also see a `SrcProcParentName` for 
parent?

**Comment by s7ryph** [comment]
Apologize, I see how the naming convention is confusing.  In the example `SrcProcName`=Parent and `TgtProcName`=Image as they would appear in a Windows log.  In this situation the `SrcProcName` would be launching the `TgtProcName` process and passing the command.  `SrcProcParentName` would be the Grandparent.

And yes I am referring to [Mavinject Inject DLL Into Running Process](https://github.com/SigmaHQ/sigma/blob/a674ee246bd02271f5e46d00010320112c9df17c/rules/windows/process_creation/proc_creation_win_creation_mavinject_process_injection.yml#L2) and the SentinelOne is also T1055 Process Injection, I should have specified.
