### ISSUE TITLE
correlate event 4625 and 4624

### ISSUE THREAD

**Issue by Hafzan-250601** [SigmaHQ/sigma#4370]
Is there any rule that can correlate event for 4625 and 4624 then it will say that brute force attempt successful?

Lets say that a hacker try to bruteforce a RDP login. An 4625 event ID will be logged right?
For successfull login and event id of 4624 will be created.

So lets say a hacker brute forcing > 10 times in 3 minutes and successfull to login into the RDP. 

The alert will say bruteforce attack successful.

Is there an alert for that? You can count this as an idea also.

Thank you in advanced!

**Comment by nasbench** [comment]
Many of the correlation rules were moved to the [deprecated](https://github.com/SigmaHQ/sigma/tree/master/deprecated) folder as they were using the old sigmac notation. 

There are many ideas (including the one you're proposing) that are not yet implemented in this repo just because the correlation engine of pySigma is still a work in progress :) 

Once its released you count on many correlation rules being present :)

Cheers.
