### ISSUE TITLE
Reduce broken links in references

### ISSUE THREAD

**Issue by martinspielmann** [SigmaHQ/sigma#4473]
### Description of the Idea

Inspired by the tweet from @Neo23x0 I thought about how dead links could be reduced. https://twitter.com/cyb3rops/status/1710573620517339203
![image](https://github.com/SigmaHQ/sigma/assets/1359917/2c4ef18c-b1d7-495b-91c1-e2b1eb62cc44)

--

### Rational

Not only acquisitions break links, also smaller blogs have a risk to disappear.

For another internal project, I created a script to check URLs against archive.org (Wayback Machine) and if not yet there, add it to the archive. If the original website disappears, it will still be present on archive.org (there may be exceptions, but chances are high).

Based on a logsource checker script by @nasbench I created the following that goes over all references:
https://gist.github.com/martinspielmann/67438435bc27ad9050185c041a5ab9fa

Does that make sense? If valuable, I'm happy to create a PR. 
Could also run in an action e.g. during PR merge.

**Comment by nasbench** [comment]
Hey @martinspielmann I like the idea. We were thinking of doing an internal archive of blogs that are referenced in Sigma rules since the whole twitter vs mastodon thingy, but this is a good start.

I don't think we can run this archiver script for every PR as it'll be time consuming especially for big PRs to check/archive every reference. But its still useful to run it regularly like every month. We can setup a monthly workflow via cron. 

I'll test the script from my side more to double check everything and then we can add it I guess.

cc @phantinuss for 2nd opinion on this.

**Comment by phantinuss** [comment]
Great idea. We can run the script as part of the releases or weekly. It seems to me it is using the resources of the archive service fairly by checking the need to archive a site first.

**Comment by nasbench** [comment]
Hey @martinspielmann thanks for the submission once again. I made some changes to the script you provided and is now in #4482 to be merged :)

I changed it from using CLI and looping over one folder at a time since it'll be run a monthly basis. I also added a cache like feature where the script will now check from a list of already archived references (I ran it locally to archive all references) and only archive new ones. In the previous state the GH workflow didn't allow it to run correctly and was taking a ton of time.

It also now creates a GH issue everytime it runs so the results can be reviewed manually.

You can check the updated version [here](https://github.com/SigmaHQ/sigma/blob/c39a0d0d5b7f7aad87831b54849e392b6c91eba2/tests/reference-archiver.py)

Cheers.

**Comment by martinspielmann** [comment]
This is so cool, thanks a lot!
