### ISSUE TITLE
FP With Rule c649a6c7-cd8c-4a78-9c04-000fc76df954

### ISSUE THREAD

**Issue by mezzofix** [SigmaHQ/sigma#4520]
### Rule UUID

c649a6c7-cd8c-4a78-9c04-000fc76df954

### Example EventLog

![image](https://github.com/SigmaHQ/sigma/assets/57439630/1c05439b-c2cf-411b-8d2c-bd6856cf2141)

### Description

Hi,

I’m a bit concerned about with the Sigma rule effectiveness. Please don’t get me wrong, I love the project and appreciate the work done here, but let’s take for example c649a6c7-cd8c-4a78-9c04-000fc76df954 The rule whitelist from what I can tell MSFT IPs, and the rule clearly states that “Legitimate use of wuauclt.exe over the network”. I’ve executed a query based on this logic over data for the past 30days and got hits for 15 unseen IP addresses (by unseen, I mean not included in the rule logic). Another issue I see, is that Windows Update is fronted by multiple global CDNs that are not MSFT property or controlled, that is from these 15 addresses few are related to CND providers , e.g.:  ctldl.windowsupdate.com CRLs are typically hosted on CDNs: 

![image](https://github.com/SigmaHQ/sigma/assets/57439630/e4b0c3fd-2905-4461-b6bf-76e2b8a23a7c)
More even, I have seen a connection initiated by wuauclt.exe from 127.0.0.1 towards 127.0.0.1 …. So, this rule can result in lots of false positives, since the IPs on the CDNs are regularly rotated, so not sure whitelisting is a viable option here. The rules status equals test “test: the rule doesn't show any obvious false positives on a limited set of test systems”. 
This isn’t about complaining, but I have few questions. Are the rules undergoing any quality checks ? In general (since im very new to Sigma rules) woud it be recommended to start with stable rules first since they “didn't produce any obvious false positives in multiple environments over a long period of time” ? 

Thanks !

**Comment by nasbench** [comment]
Thanks for reporting this @mezzofix 

Let me tackle some of the point you mentioned :)

FIrst of all a false positive is always to be expected in some form with a rule even a stable or critical sometime. The best you can do as a community member who has enough test data is to report things as you're doing right now. So that the issue can be handled either by reducing the level, updating the logic or simply deprecating the rule if its too prone to FP.

Second, a rule logic can't always be perfect in this case the rule was written 3+ years ago as you can see and it didn't get any FP reported by the limited test systems nor by community members hence it gets upgraded to test automatically.

If you have found more FPs report them :) this is how community detections get enhanced. Not by bashing the rules themselves and questioning the quality ;) (even though you just started using them as you said)

I will look into this rule and report back

**Comment by mezzofix** [comment]
@nasbench I didn’t want to sound rude or anything, apologize if I sounded like that (English is not my first language). I appreciate your efforts. Would it be possible to, that’s just an idea to include steps for re-producing the technique a give Sigma rule is covering? What I mean by that is, for example, af77cf95-c469-471c-b6a0-946c685c4798, can be easily validated with https://atomicredteam.io/defense-evasion/T1218/#atomic-test-9---load-arbitrary-dll-via-wuauclt-(windows-update-client)

**Comment by nasbench** [comment]
@mezzofix no worries. Its just sometimes people get the wrong idea about the Sigma project and neglect the effort that goes into maintaining such a large ruleset. I really appreciate it when people contribute, especially FPs because that helps everyone down the line. So thanks for taking the time :)

As for your suggestion. As tweeted [here](https://twitter.com/nas_bench/status/1716953295972163850). Atomic red team integration (and more) are coming very soon the project to help people validate these detections (just a few more weeks, I'm still making the finishing touches).

**Comment by mezzofix** [comment]
> Its just sometimes people get the wrong idea about the Sigma project and neglect the effort that goes into maintaining such a large ruleset.

 I’m to blame as well, I think people (same as I did) have the false perception of it being the cure for all problems, and I see now and agree, the scale is immense, and maintaining it is a challenge. Looking forward towards the mentioned integrations !

**Comment by nasbench** [comment]
This issues will resolved in #4564

The rule now enforces the presence of CLI in the network event as an enrichment to avoid FP and a definition has been added to indicate this. Without it the rule doesn't make sense and would be demoted to informational / low (at best).  This way even people who do not read the rule will not make use of it and won't trigger in the first place :)

Thanks once again for reporting this.
