### ISSUE TITLE
Adding Mitre Detection ID to Rule Tags 

### ISSUE THREAD

**Issue by AdmU3** [SigmaHQ/sigma#4622]
### Adding Mitre Detection id to sigma rule tag 

This is a proposal to be able to include the detection ID to the rule tag along with other tags
e.g: detection.ds0009

https://sigmahq.io/sigma-specification/Tags_specification.html
namespace: detection

_

> Use the detection tag to indicate the type of a rule. Example tag: detection.threat_hunting.
> 
>     dfir
>     emerging_threats
>     threat_hunting

_

**Comment by phantinuss** [comment]
Sigma is way more specific (up to technically parseable) with the `logsource` section. 

If I am not misunderstanding DS is the datasource mapping of MITRE, not "detection ID". So this would be a static mapping of logsource to DS. I don't really see the benefit because as I said the logsource information is of higher quality than the MITRE DS information.

I understand that these datasource ids could be used downstream for mapping but I don't feel like manually doing duplicate work during rule creation. But that's just my personal opinion. Let's see what others think.

**Comment by AdmU3** [comment]
Thank you, I got your point, I will add the combined DS id and technique in the rule name .
I believe checking the technique id along with the data source id in the MITRE  will provide better understanding for the rule " Detects column"
