### ISSUE TITLE
Question - Event sequencing

### ISSUE THREAD

**Issue by plushed** [SigmaHQ/sigma#533]
Hello,

I was wondering if you could tell me if there are any plans or already a way for Sigma to identify event sequencing. I know it handles conditions (e.g. condition a AND condition b.) but how can you consider something like 'condition a THEN condition b'? Are there any specifications for adding time constraints or windows to the rule sets?

Apologies if this is documented and I missed it. 

Thanks

**Comment by thomaspatzke** [comment]
There's a _near_ operator that can be used in conditions but it is not very well supported and misses features required for expression of event sequences. I'm currently working on a better way to express such things.

**Comment by gaelmuller** [comment]
Hello,

Is there any draft or ETA on this ?

It could be interesting to be able to define rules such as:

`more than 3 failed login attempts followed by a successful login, from the same IP address`

I think that the main features needed are:

* Define different conditions that need to match different events in any order (within the timeframe)
* Define different conditions that need to match different events in a specific order (within the timeframe)
* Define what the different events should have in common. When creating rules for event sequencing, we usually want to group events by some value (such as an IP address in previous example). We also have to take into consideration that the fields may not be the same in different log events.

**Comment by thomaspatzke** [comment]
No ETA on this, as this is a rather complex task to build a generic way to describe such relationships in a vendor-agnostic way. This is caused by the fact that the way to express this in different systems is completely different and sometimes even only possible by usage of workarounds and approximations.

**Comment by malvidin** [comment]
I agree that each backend would need its own implementation, but comparing to this rule (and ignoring the issues with the strings likely not matching the intended activity):
https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_apt_turla_commands.yml

The modification to use `before` or `after` is simple with additional aggregation functions. 
```
detection:
   netCommand1:
      CommandLine: 'net view /DOMAIN'
   netCommand2:
      CommandLine: 'net session'
   netCommand3:
      CommandLine: 'net share'
   timeframe: 1m
   condition: netCommand1 | after netCommand2 and netCommand3
```

Limitations of multiple (or all) vendors raising an implementation error does not appear to impact the ability of Sigma to clearly express the relationship.

If the issue is that `near`/`after`/`before` are inappropriately being included as aggregation functions, then removing `near` would be consistent, while a way to describe these relationships developed.

**Comment by thomaspatzke** [comment]
The near operator will be replaced with a YAML based construct to describe relationships between different events matched by sigma rules.

Anyways, no ETA yet. Long way to go.

**Comment by malvidin** [comment]
Should the `near` operator be removed until that work is done? Multiple rules include that operator, and the specification wiki includes a definition and usage. 

Should the `near` operator be more similar to the SQL `NEAR` , and be applied as a condition between multiple terms? With a different term used for temporal or network proximity?

**Comment by thomaspatzke** [comment]
I think best would be to keep it until we have something new and never allocate the few resources we have to fix something that will be gone in the next time. Elsewhere we Also would have to drop some rules that use near.
